
--Truncate
CREATE TABLE EJEMPLO(
	campo1 INT IDENTITY(1,1),
	campo2 INT,
	campo3 INT
	)

SELECT * FROM EJEMPLO

INSERT INTO EJEMPLO(campo2, campo3)
VALUES (32,12)

TRUNCATE TABLE EJEMPLO